import React from 'react';

export default function App({ remoteMarkup }) {
  return (
    <main style={{ fontFamily: 'sans-serif', margin: '2rem auto', maxWidth: 720 }}>
      <h1>React SSR + Webpack Module Federation</h1>
      <p>Host is server-rendered and injects SSR markup generated by a remote microfrontend.</p>
      <section id="remote-slot" dangerouslySetInnerHTML={{ __html: remoteMarkup }} />
    </main>
  );
}
