const http = require('http');
const fs = require('fs');
const path = require('path');
const { renderFancyCard } = require('./ssr');

const port = 3001;
const remoteEntryPath = path.resolve(__dirname, './remoteEntry.js');

function sendJson(res, status, payload) {
  const body = JSON.stringify(payload);
  res.writeHead(status, {
    'Content-Type': 'application/json; charset=utf-8',
    'Content-Length': Buffer.byteLength(body)
  });
  res.end(body);
}

const server = http.createServer((req, res) => {
  const url = new URL(req.url, `http://${req.headers.host}`);

  if (url.pathname === '/health') {
    sendJson(res, 200, { status: 'ok', service: 'remote' });
    return;
  }

  if (url.pathname === '/remoteEntry.js') {
    const code = fs.readFileSync(remoteEntryPath, 'utf8');
    res.writeHead(200, { 'Content-Type': 'text/javascript; charset=utf-8' });
    res.end(code);
    return;
  }

  if (url.pathname === '/ssr') {
    const title = url.searchParams.get('title') || 'Rendered on remote server';
    const body = url.searchParams.get('body') || 'This HTML is generated by the remote microfrontend.';
    sendJson(res, 200, { html: renderFancyCard({ title, body }) });
    return;
  }

  sendJson(res, 404, { error: 'not found' });
});

server.listen(port, () => {
  console.log(`remote listening on http://localhost:${port}`);
});
